### PR TITLE
Sdk 274 settings at one place

### PR DESCRIPTION
**Pull request by bwand**
All names for nJAMS SDK settings are now located in file NjamsSettings.java.

All occurences inside the SDK are refactored and the old static strings around the different SDK parts are set to deprecated.

### CODE REVIEW

**Comment by scipper** [comment]
What do you think about creating sub classes for every settings category, which are nested in NjamsSettings like `public static final SdkSettings SDK = new SdkSettings();`. And SdkSettings contains all sdk related fields as `public final String PROPERTY_XY`.

**Comment by bwand** [comment]
> What do you think about creating sub classes for every settings category, which are nested in NjamsSettings like `public static final SdkSettings SDK = new SdkSettings();`. And SdkSettings contains all sdk related fields as `public final String PROPERTY_XY`.

In my opinion this does not really help. To find the properties you search, it is easy to use autocomplete and type something like JMS....

And the Structure of the NjamsSettings File is currently flat and organized by BANNERS.... Wen do not have hundreds of properties.

@fs-chris Your opinion?

**Comment by bwand** [comment]
As suggested by @scipper I will replace the Deprecated Strings with the ones from NjamsSettings....

`    @Deprecated
    public static final String CONNECTION_FACTORY = NjamsSettings.PROPERTY_JMS_CONNECTION_FACTORY;`

**Comment by fs-chris** [comment]
> > What do you think about creating sub classes for every settings category, which are nested in NjamsSettings like `public static final SdkSettings SDK = new SdkSettings();`. And SdkSettings contains all sdk related fields as `public final String PROPERTY_XY`.
> 
> In my opinion this does not really help. To find the properties you search, it is easy to use autocomplete and type something like JMS....
> 
> And the Structure of the NjamsSettings File is currently flat and organized by BANNERS.... Wen do not have hundreds of properties.
> 
> @fs-chris Your opinion?

I think we should not spend too much work into this refactoring because the main issue remains: that the settings or keys are simple untyped strings. 
The new sorting is good enough for lookup and as a reference.
We could add additional grouping as Steffen suggests but it's not really necessary, I think.

**Review by fs-chris — APPROVED** [review]

**Pull request merged**
